# Generated by Django 6.0.3 on 2026-05-06 21:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('emails_cc', models.TextField(blank=True, help_text='Correos para copia separados por coma')),
            ],
        ),
        migrations.CreateModel(
            name='ViajePernoctacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10)),
                ('conductor', models.CharField(max_length=150)),
                ('fecha_servicio', models.DateField()),
                ('token_acceso', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('link_respondido', models.BooleanField(default=False)),
                ('lugar_pernoctacion', models.CharField(blank=True, max_length=255, null=True)),
                ('requiere_extension', models.BooleanField(default=False)),
                ('motivo_extension', models.TextField(blank=True, null=True)),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('perdida_senal', models.BooleanField(default=False)),
                ('observacion_monitoreo', models.TextField(blank=True, null=True)),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_logistica.transportista')),
            ],
        ),
    ]
