# Generated by Django 6.0.3 on 2026-05-06 23:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_logistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viajepernoctacion',
            options={'verbose_name': 'Viaje de Pernoctación', 'verbose_name_plural': 'Viajes de Pernoctación'},
        ),
        migrations.RemoveField(
            model_name='transportista',
            name='emails_cc',
        ),
        migrations.RemoveField(
            model_name='viajepernoctacion',
            name='motivo_extension',
        ),
        migrations.RemoveField(
            model_name='viajepernoctacion',
            name='observacion_monitoreo',
        ),
        migrations.RemoveField(
            model_name='viajepernoctacion',
            name='perdida_senal',
        ),
        migrations.RemoveField(
            model_name='viajepernoctacion',
            name='requiere_extension',
        ),
        migrations.AlterField(
            model_name='transportista',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='viajepernoctacion',
            name='conductor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='viajepernoctacion',
            name='fecha_servicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
